Errors now sent to stderr instead of stdout

diff --git a/trunk/bin/addgroup b/trunk/bin/addgroup
--- a/trunk/bin/addgroup
+++ b/trunk/bin/addgroup
@@ -53,7 +53,7 @@ do
 done
 
 if [ -z "$group" ]; then
-	echo "Error: --group was not specified"
+	echo "Error: --group was not specified" >&2
 	exit 1
 fi
 
@@ -69,7 +69,7 @@ DESTINATION="$DEST_DIRECTORY/$group.cfg"
 if [ -z "$FORCE" ]; then
 	# Abort if destination file already exists
 	if [ -f $DESTINATION ]; then
-		echo "ERROR: File $DESTINATION already exists. Use --force to overwrite"
+		echo "ERROR: File $DESTINATION already exists. Use --force to overwrite" >&2
 		exit 1
 	fi
 	# Abort if group already exists in Nagios
@@ -77,7 +77,7 @@ if [ -z "$FORCE" ]; then
 		grep $i /var/log/nagios/objects.cache | awk '{ print $2 }' | grep -q -w $group
 		RESULT=$?
 		if [ $RESULT -eq 0 ]; then
-			echo "ERROR: $i $group already exists in nagios configuration. Use --force to write config anyway"
+			echo "ERROR: $i $group already exists in nagios configuration. Use --force to write config anyway" >&2
 			exit 1
 		fi
 	done
diff --git a/trunk/bin/addhost b/trunk/bin/addhost
--- a/trunk/bin/addhost
+++ b/trunk/bin/addhost
@@ -72,7 +72,7 @@ done
 if [ -z "$ipaddress" ]; then
 	TMP=`host $hostname | grep "has address"`
 	if [ $? -gt 0 ]; then
-		echo "could not locate ip address for host $hostname. Try using --ip paramater"
+		echo "Error: could not locate ip address for host $hostname. Try using --ip paramater" >&2
 		exit 1
 	fi
 	ipaddress=`echo $TMP | awk '{ print $4 }'`
@@ -82,7 +82,7 @@ fi
 DEST_DIRECTORY=$DEST_DIRECTORY/$group
 test -d "$DEST_DIRECTORY" || mkdir -p "$DEST_DIRECTORY"
 if [ $? -gt 0 ]; then
-	echo "ERROR: Could not create directory $DEST_DIRECTORY"
+	echo "ERROR: Could not create directory $DEST_DIRECTORY" >&2
 	exit 1
 fi
 
@@ -90,7 +90,7 @@ DESTINATION="$DEST_DIRECTORY/$hostname-host.cfg"
 
 if [ -z "$FORCE" ]; then
 	if [ -f $DESTINATION ]; then
-		echo "ERROR: File $DESTINATION already exists. Use --force to overwrite"
+		echo "ERROR: File $DESTINATION already exists. Use --force to overwrite" >&2
 		exit 1
 	fi
 fi
diff --git a/trunk/bin/addtemplate b/trunk/bin/addtemplate
--- a/trunk/bin/addtemplate
+++ b/trunk/bin/addtemplate
@@ -63,7 +63,7 @@ fi
 
 FILENAME=`findhost $hostname`
 if [ $? -gt 0 ]; then
-	echo "Host $hostname not found"
+	echo "Host $hostname not found" >&2
 	exit 1
 fi
 
@@ -73,13 +73,13 @@ DEST_DIRECTORY=`dirname $FILENAME`
 DESTINATION="$DEST_DIRECTORY/$hostname-$template.cfg"
 TEMPLATE=$TEMPLATE_DIR/$template.cfg-example
 if [ ! -f "$TEMPLATE" ]; then
-	echo "ERROR: No such file or directory: $TEMPLATE"
+	echo "ERROR: No such file or directory: $TEMPLATE" >&2
 	exit 1
 fi
 
 if [ -z "$FORCE" ]; then
         if [ -f $DESTINATION ]; then
-                echo "ERROR: File $DESTINATION already exists. Use --force to overwrite"
+                echo "ERROR: File $DESTINATION already exists. Use --force to overwrite" >&2
                 exit 1
         fi
 fi
@@ -99,7 +99,7 @@ fi
 
 cat $TEMPLATE | sed "s/IPADDR/$ipaddress/g" | sed "s/HOSTNAME/$hostname/g" | sed "s/GROUP/$group/g" > $DESTINATION
 if [ $? -gt 0 ]; then
-	echo "Error writing to $DESTINATION"
+	echo "Error writing to $DESTINATION" >&2
 	exit 1
 fi
 echo "Template $template successfully added to $DESTINATION"
